name: Request a feature
description: Suggest an idea for EOCLU.
labels: ["enhancement"]
assignees:
  - LibertyNJ
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature!

        Please enter a short, descriptive title above.

        The request will be reviewed, but there is no guarantee that it will be
        implemented.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the problem that you’d like to solve.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe your ideal solution to the problem.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this feature request, you agree to follow our
        [Code of Conduct](https://github.com/LibertyNJ/eoclu?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
