name: Continuous Integration
run-name: "Continuous Integration of ${{ github.ref_name }}"
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  RUSTFLAGS: -Dwarnings
jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner: ubuntu-latest
          - name: macOS
            runner: macos-latest
          - name: Windows
            runner: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --locked --verbose
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --all --check --verbose
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Lint
        run: |
          cargo clippy --verbose \
          -- -Dclippy::all -Dclippy::cargo -Dclippy::pedantic
